### PR TITLE
Implemented counting sort

### PR DESCRIPTION
**Pull request by jarettgross**
Implemented counting sort algorithm, placed it under "Sorting"

### CODE REVIEW

**Comment by parkjs814** [comment]
Thanks for contributing.
For the next time, can you run `gulp` or `gulp build` before you push it?
Since files in `/public` directory are automatically built, they should not be changed unless you changed stylesheet or javascript files.

**Comment by jarettgross** [comment]
Sure thing. I tried doing that the past couple of times, but it looks as though 15+ files are changed after I run gulp even though I didn't touch them. Am I supposed to commit all of those modified files every time I make a change?

**Comment by parkjs814** [comment]
Never mind, this may not be your fault.
I will figure out how to automatically build those files when merging.

**Comment by duaraghav8** [comment]
@parkjs814  https://libraries.io/npm/javascript-gulp-precommit
not sure but might help

**Comment by parkjs814** [comment]
Actually gulp should build after we merge the pull request, not before pushing it.
I don't know what to do hmm..

**Comment by TornjV** [comment]
@parkjs814 We could use travis.

**Comment by parkjs814** [comment]
@TornjV Isn't travis only for the deployment to server?

**Comment by nem035** [comment]
@TornjV might be on to something: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by parkjs814** [comment]
Mhm that can be one possible solution.
I guess it is time to move to AWS or Heroku, there are too many limitations as well as this issue.

**Comment by jarettgross** [comment]
@parkjs814, so for future commits, should I run gulp before pushing, or just push files that I explicitly changed?

**Comment by parkjs814** [comment]
@jarettgross,
I figured out that there will be no difference whether you run gulp or not.
Don't worry about this issue, and just send a pull request.
I will care about it.
Sorry for the inconvenience.

**Pull request merged**
