### PR TITLE
Made changes to the efficient bridge-finding algorithm

### PR DESCRIPTION
**Pull request by fclvbfm934**
Ignore the server.py file, that was just so I could run it on localhost. 

I made some changes to the efficient bridge-finding algorithm (the non-naive one):

1. Added a description of the algorithm
2. Made some changes to the algorithm. Removed the visited[] and parent[] arrays, and used -1 to indicate non-visited. 
3. Also changed the algorithm a bit, so that when a cycle is hit, the DFS can directly change the values of low[]
4. Also edited the tracing, defining a trace() function and then placing it after each visit (makes more sense that way).

### CODE REVIEW

**Comment by TornjV** [comment]
There are extra files and conflicts weren't dealt with. Please send another pr after just making fixes around the bridge finding algorithm.

**Comment by fclvbfm934** [comment]
I only changed things around the bridge finding algorithm. I did periodically update from the parkjs814 gh-pages branch, and when I send in the pr it has hundreds of file having no changes except for the "File mode changed". How should I get rid of that?

**Comment by nem035** [comment]
Hi @fclvbfm934, a few suggestions:

1. You don't need to create a `server.py`. Since you have python installed, you can just run `python -m SimpleHTTPServer` and that's it.

2. As far as all the file modes changing,  [take a look at this Stackoverflow issue]( http://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha)

**Comment by fclvbfm934** [comment]
Hi, 
I removed server.py already. Thanks! 

Regarding the file modes, I tried typing that into the shell and the pull request still has the file mode changes. I'm kind of new to using GitHub so I'm not quite sure what to do. (sorry if this is a dumb question). I'm using the GitHub Desktop application, so what should I do to get rid of this file mode change?

**Pull request closed without merging**
