### PR TITLE
Ceasar cipher fix-Encrypt string with spaces

### LINKED ISSUE #144: Caesar Cipher - string with space
untitled

string with space can not encrypt correctly.

### PR DESCRIPTION
**Pull request by archie94**
Fixes #144

### CODE REVIEW

**Comment by nem035** [comment]
Hey @archie94, this isn't really the best way to handle this, the problem is basically if the user enters anything not in the alphabet, not just spaces. Otherwise we'll get issues in the future for punctuation, capitalization etc.

The condition 

```js
if (currChar !== ' ')
```

Isn't enough. It should check if the alphabetMap contains the character:

```js
if (typeof alphabetMap[currChar] !== 'number')
```

This way encryption would would encrypt anything in the provided `alphabet` and ignore anything else.

Can you make this update and then we'll merge the pull request?

**Comment by archie94** [comment]
@nem035 Thanks a lot! This is real stupid of me! Yeah I will make the changes and then you can mege. 

Thanks again!

**Comment by archie94** [comment]
@nem035 Please check!

**Comment by nem035** [comment]
Seems ok to me :)

**Pull request merged**
