### PR TITLE
Add FloodFill Algorithm

### PR DESCRIPTION
**Pull request by olambdao**
hi, I added an flood-fill.
put this etc category. is it right?

### CODE REVIEW

**Comment by TornjV** [comment]
It's fine, although I would remove the _denotify and _deselect calls in data.js.

**Comment by olambdao** [comment]
why remove _denotify and _deselect?

**Comment by TornjV** [comment]
It would make the visualization prettier imo.
Also, every visualization I've seen has visited areas colored.

**Comment by olambdao** [comment]
i agree too, i removed that!

**Pull request merged**
