### PR TITLE
Fullscreen

### PR DESCRIPTION
**Pull request by parkjs814**

### CODE REVIEW

**Comment by duaraghav8** [comment]
awesome!

**Comment by parkjs814** [comment]
@duaraghav8 Thanks for your great idea 😁

**Comment by duaraghav8** [comment]
Inspired from Hackerrank :P
Could you please tell me why you chose to instead hard-code the vendor-specific functions in the updated enable_fullscreen.js?
Is this choice due to speed? (because my reasoning was that the code could be space-wise efficient if we didn't hard-code)

**Comment by parkjs814** [comment]
There may not be so much difference in speed though, I found out that some of the function names are {prefix}Full**S**creen and others are {prefix}Full**s**creen, which is crappy 😂.

**Comment by duaraghav8** [comment]
yea that was a facepalm moment for me too

**Pull request merged**
