### PR TITLE
Ceasar cypher

### PR DESCRIPTION
**Pull request by nem035**
Added Cryptography category and the [Caesar Cipher](https://en.wikipedia.org/wiki/Caesar_cipher) algorithm.

Here's a sample of the encryption part:
caesar cipher

There's decryption as well, I just cut it from the gif to not make it too long. First tracer encrypts the string and then the second one decrypts it back to the original.

Since the algorithm requires to update the array (by rotating characters in-place) while traversing it, I added code (the `setValue` function) to set a single value in [`Array1DTracer`](https://github.com/parkjs814/AlgorithmVisualizer/pull/83/files#diff-383b77fb5e330c1046ebcfa42c5e6300R34), [`Array2DTracer`](https://github.com/parkjs814/AlgorithmVisualizer/pull/83/files#diff-21789d85d376a0ee49671c8aae78f18cR154) and [`Tracer`](https://github.com/parkjs814/AlgorithmVisualizer/pull/83/files#diff-342db3ec6327175cd74cc88d1ffbd9cdR20), since there was previously only the `setData` function which sets all the data. I figure this feature will be useful for any algorithm that needs to make updates while executing.

Another thing, since this algorithm uses strings instead of numbers in the arrays, I refactored the calls to `refineNumber` to call `refinePrimitiveByType` which will perform the needed operation based on the argument type (only numbers and strings for now).

<hr />

Side note, let me know if you guys don't want me to apply [js-beautify](https://github.com/beautify-web/js-beautify) whenever I make a pull request. I figure it doesn't hurt but still want to hear your thoughts on it. Perhaps we should add a linter ([js-hint](https://github.com/jshint/jshint) or [es-lint](https://github.com/eslint/eslint)) as part of the project to standardize code formatting?

### CODE REVIEW

**Comment by nem035** [comment]
I just saw that `tracer._notify` already had the functionality to update individual values via second argument.
I will close this pull request and remove the changes related to `setValue` before making a second pull request.

**Comment by parkjs814** [comment]
I love that Cryptography category is added!
I think we need to put the documentation beside the scratch paper to clarify the methods.
For `refinePrimitiveByType` method it makes much sense, but how do you think about renaming it to `refine` since it is going to be used a lot?
Thanks for your work!

**Comment by nem035** [comment]
Yessir, documentation, at least for the main methods, would definitely be useful.

As far as `refinePrimitiveByType`, the reason I like that (or something as verbose) better is because useful function names eliminate (or at least reduce) the need for documentation since the name itself describes what the code does. 

I would go furthermore and suggest to update some other functions and variables with more meaningful names: for example, `tm` inside `/js/module/tracer.js` can be called `manager`, or even `tracerManager`. A few extra characters don't hurt the code efficiency but can make a difference when somebody new is looking at the code for the first time.

Of course, [adding modules](https://github.com/parkjs814/AlgorithmVisualizer/issues/48) would make all of this much cleaner and easier, and remove the global space pollution that currently exists 😉

**Comment by parkjs814** [comment]
You are totally right.
I will see if there is any other variable with unclear name such as `tm`.
Also, I will work on rewriting in ES6 soon.
Thank!

**Pull request closed without merging**
