### PR TITLE
Auto generate tracers

### PR DESCRIPTION
**Pull request by nadr0**
finally got a working version with array1D/2D tracers. 

When clicking generate at the top a new div pops up and you can create array 1d/2d tracers. The user can click inside each element in the matrix and edit it to any numeric value then press the generate JS and the code will appear in the tracer below. After this the user can copy and paste the code into the data.js file or the scratch pad. 

what I like
- I got to use similar code for 1d/2d array creation
- a div overlay that just pops up for you can create these in any algorithm example and close it and it brings you back to the example

what I don't like
- the visuals for the input fields and buttons
 - needs to look cleaner
- createHTML() function in js/create/index.js (it works though)

todos:
- add chart tracer
- add graph tracer

### CODE REVIEW

**Comment by parkjs814** [comment]
I have tested this on Chrome, Safari, and Firefox, but it doesn't work on any of those.
It is unable to change columns and rows, create matrices, generate Javascript.
Could you check it again?

**Comment by nadr0** [comment]
Interesting, its working for me on the website. Is there any console errors?

**Comment by parkjs814** [comment]
I don't see any errors in console.

**Comment by nadr0** [comment]
Since you merged it to master its up on the site, I don't see any issues with it. I have tried on my computer and several other and it works fine, I have been testing in Chrome. Maybe some screen shots or video of the issues you are having?

**Pull request merged**
