### PR TITLE
Updated setup_top_menu.js 

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Updated `setup_top_menu.js` to change the text displayed on start button from "Start" -> "Reset" after the button is clicked.  The button does the reset job if it is clicked after starting...
Its just a suggestion.. what did you say @parkjs814 ?

### CODE REVIEW

**Comment by parkjs814** [comment]
Hmm.. `Reset` sounds like `Stop` more than `Run Again`.
How do you think of `Rerun` instead?

**Comment by gautamkrishnar** [comment]
Yes That's good :+1:

**Comment by gautamkrishnar** [comment]
@parkjs814 Updated :smile:

**Comment by parkjs814** [comment]
After the algorithm finishes running, the button may still be `Rerun` instead of `Run`. I will fix it.

**Pull request merged**
